import type { StoredColoringPage } from "./coloringPageTypes";

/** Seed list until Debbie saves from the CMS. Existing print-ready assets stay in /public. */
export const DEFAULT_COLORING_PAGES: StoredColoringPage[] = [
  {
    id: "cp-benji",
    slug: "benji",
    name: "Benji",
    file: "/coloring-pages/benji.jpg",
    orientation: "portrait",
    alt: "Benji the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-boone",
    slug: "boone",
    name: "Boone",
    file: "/coloring-pages/boone.jpg",
    orientation: "landscape",
    alt: "Boone the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-charlie",
    slug: "charlie",
    name: "Charlie",
    file: "/coloring-pages/charlie.jpg",
    orientation: "portrait",
    alt: "Charlie the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-covey",
    slug: "covey",
    name: "Covey",
    file: "/coloring-pages/covey.jpg",
    orientation: "portrait",
    alt: "Covey the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-dexter",
    slug: "dexter",
    name: "Dexter",
    file: "/coloring-pages/dexter.jpg",
    orientation: "landscape",
    alt: "Dexter the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-khaki",
    slug: "khaki",
    name: "Khaki",
    file: "/coloring-pages/khaki.jpg",
    orientation: "portrait",
    alt: "Khaki the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-kylo-ren",
    slug: "kylo-ren",
    name: "Kylo-Ren",
    file: "/coloring-pages/kylo-ren.jpg",
    orientation: "portrait",
    alt: "Kylo-Ren the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-lexie",
    slug: "lexie",
    name: "Lexie",
    file: "/coloring-pages/lexie.jpg",
    orientation: "portrait",
    alt: "Lexie the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-lily",
    slug: "lily",
    name: "Lily",
    file: "/coloring-pages/lily.jpg",
    orientation: "portrait",
    alt: "Lily the therapy dog — printable coloring page",
    active: true,
  },
  {
    id: "cp-sam",
    slug: "sam",
    name: "Sam",
    file: "/coloring-pages/sam.jpg",
    orientation: "portrait",
    alt: "Sam the therapy dog — printable coloring page",
    active: true,
  },
];
